apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
labels:
  - pairs:
      project-id: "fridge-stats-demo-001"
      app.kubernetes.io/part-of: "fridge-stats"
      app.kubernetes.io/managed-by: "kustomize"
images:
  - name: REPLACE_WITH_YOUR_REGISTRY/stats-api
    newName: 744139897900.dkr.ecr.us-east-1.amazonaws.com/fridge-stats-api
    newTag: 0.4.0
  - name: REPLACE_WITH_YOUR_REGISTRY/stats-ui
    newName: 744139897900.dkr.ecr.us-east-1.amazonaws.com/fridge-stats-ui
    newTag: 0.4.0
patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: StatefulSet
      name: postgres
      namespace: demo
    patch: |-
      [
        {"op":"add","path":"/spec/volumeClaimTemplates/0/spec/storageClassName","value":"gp2"}
      ]
