apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/part-of: fridge-stats
    app.kubernetes.io/managed-by: envsubst
    project-id: "${PROJECT_ID}"
  name: postgres-secret
  namespace: ${NAMESPACE}
type: Opaque
stringData:
  POSTGRES_DB: appdb
  POSTGRES_USER: appuser
  POSTGRES_PASSWORD: apppassword
